apiVersion: v1
kind: Namespace
metadata:
  name: fluentlogging
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluent-bit
  namespace: fluentlogging
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::177716289679:role/FluentBitOpenSearchRole
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluent-bit
rules:
- apiGroups: [""]
  resources:
  - namespaces
  - pods
  - nodes
  - nodes/proxy
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluent-bit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluent-bit
subjects:
- kind: ServiceAccount
  name: fluent-bit
  namespace: fluentlogging
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: fluentlogging
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        900
        Log_Level    info
        Parsers_File parsers.conf

    @INCLUDE jenkins.conf
    @INCLUDE argocd.conf

  jenkins.conf: |
    [INPUT]
        Name              tail
        Path              /var/log/containers/jenkins-0*.log
        Parser            jenkins_logs
        Tag               jenkins.*
        DB                /var/log/flb_jenkins.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10

    [FILTER]
        Name              kubernetes
        Match             jenkins.*
        Kube_Tag_Prefix   jenkins.var.log.containers.
        Merge_Log         On
        Keep_Log          On
        K8S-Logging.Parser On
        K8S-Logging.Exclude Off

    [FILTER]
        Name    modify
        Match   jenkins.*
        Rename  ts @timestamp
        Rename  msg message
        Rename  level log.level

    [OUTPUT]
        Name              opensearch
        Match             jenkins.*
        Host              fi454c4jzlbdxrvzw2c2.ap-northeast-2.aoss.amazonaws.com
        Port              443
        Logstash_Format   On
        Logstash_Prefix   jenkins
        tls               On
        tls.verify        On
        AWS_Auth          On
        AWS_Region        ap-northeast-2
        AWS_Service_Name  aoss
        Suppress_Type_Name On

  argocd.conf: |
    [INPUT]
        Name              tail
        Path              /var/log/containers/argocd-application-controller*.log
        Parser            cri
        Tag               argocd.controller
        DB                /var/log/flb_argocd_controller.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10

    [FILTER]
        Name              kubernetes
        Match             argocd.controller.*
        Kube_Tag_Prefix   argocd.controller.var.log.containers.
        Merge_Log         On
        K8S-Logging.Parser On
        K8S-Logging.Exclude Off

    [FILTER]
        Name    parser
        Match   argocd.controller.*
        Key_Name log
        Parser   argocd_json
        Reserve_Data On

    [FILTER]
        Name    modify
        Match   argocd.controller.*
        Rename  time @timestamp
        Rename  msg message
        Rename  level log.level
        Remove  log

    [OUTPUT]
        Name              opensearch
        Match             argocd.controller.*
        Host              fi454c4jzlbdxrvzw2c2.ap-northeast-2.aoss.amazonaws.com
        Port              443
        Logstash_Format   On
        Logstash_Prefix   argocd-controller
        tls               On
        tls.verify        On
        AWS_Auth          On
        AWS_Region        ap-northeast-2
        AWS_Service_Name  aoss
        Suppress_Type_Name On

  parsers.conf: |
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On

    [PARSER]
        Name        cri
        Format      regex
        Regex       ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<log>.*)$
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%LZ

    [PARSER]
        Name        argocd_json
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%SZ
        Time_Keep   On

    [PARSER]
        Name        jenkins_logs
        Format      regex
        Regex       ^\S+ \S+ \S+ (?<ts>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d{3}\+\d{4}) \[id=\d+\]\s+(?<level>\S+)\s+(?<logger>[^:]+): (?<msg>.*)$
        Time_Key    ts
        Time_Format %Y-%m-%d %H:%M:%S.%L%z

    [PARSER]
        Name        grafana_logs
        Format      regex
        Regex       ^(?<log_time>\S+) \S+ \S+ logger=(?<logger>\S+) t=(?<ts>\S+) level=(?<level>\S+) msg="(?<msg>[^"]+)"(?: duration=(?<duration>\S+))?$
        Time_Key    ts
        Time_Format %Y-%m-%dT%H:%M:%S.%LZ

    [PARSER]
        Name        argocd_firstline
        Format      regex
        Regex       ^(?<time>[^ ]+) (?<stream>stdout|stderr) F (?<log>.*)$
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%LZ
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: fluentlogging
  labels:
    app: fluent-bit
spec:
  selector:
    matchLabels:
      app: fluent-bit
  template:
    metadata:
      labels:
        app: fluent-bit
    spec:
      serviceAccountName: fluent-bit
      terminationGracePeriodSeconds: 10
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      containers:
        - name: fluent-bit
          image: public.ecr.aws/aws-observability/aws-for-fluent-bit:2.33.1
          securityContext:
            privileged: true
            runAsUser: 0
          resources:
            limits:
              memory: 100Mi
              cpu: 200m
            requests:
              memory: 50Mi
              cpu: 50m
          volumeMounts:
            - name: config
              mountPath: /fluent-bit/etc/
            - name: varlog
              mountPath: /var/log
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: varlogpods
              mountPath: /var/log/pods
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: fluent-bit-config
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: varlogpods
          hostPath:
            path: /var/log/pods
