apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudwatch-datasource-rds
  namespace: metric
  labels:
    grafana_datasource: "1"
data:
  cloudwatch.yaml: |-
    apiVersion: 1
    datasources:
    - name: CloudWatch-RDS
      uid: cloudwatch-rds
      type: cloudwatch
      access: proxy
      jsonData:
        authType: default
        defaultRegion: ap-northeast-2